### ISSUE TITLE
/test/./test_various.rb:175 failing on various archs with 2.15.1

### ISSUE THREAD

**Issue by boutil** [ohler55/oj#303]
Hi,

When I prepared the Debian package for oj 2.15.1, I noticed a test failure on the following architectures: armel, armhf, i386, powerpc, mips,...
```
-------- running ./test/./test_various.rb test ------- 
Run options: --seed 50778

# Running:

F............................................................................................................................

Finished in 0.025302s, 4940.2725 runs/s, 8536.7909 assertions/s.

  1) Failure:
Juice#test_float_parse [./test/./test_various.rb:175]:
Expected: Float
  Actual: BigDecimal

125 runs, 216 assertions, 1 failures, 0 errors, 0 skips
```

See https://buildd.debian.org/status/package.php?p=ruby-oj
Everything is fine on 64 bit architectures like amd64, arm64,ppc64el, etc.
I'd be happy to test things with your guidance if needed.

Cheers,

Cédric

**Comment by ohler55** [comment]
I'll look at it this weekend or maybe tomorrow. I suspect it might be a configuration option issue. I hope so anyway.

**Comment by ohler55** [comment]
The problem is indeed 32 vs 64 bit as far as floats are concerned or at least the precision of floats. Can you tell me what the value of RUBY_PLATFORM is?

**Comment by ohler55** [comment]
Never mind. I found a better work around to keep parsing the same on 64 and 32. Please give the current candidate on github a try.

**Comment by boutil** [comment]
All tests pass on armel and armhf. I haven't tested the other architectures, but I guess it will be good. Thanks!

**Comment by ohler55** [comment]
Great I'll make a release once I get confirmation on the other outstanding issue addressed by this release.

**Comment by boutil** [comment]
Hi!

The problem is still present on a subset of the architectures with 2.16.1. Archs currently failing are in Debian are all i386-based (linux i386, hurd i386 [1] and freebsd i386). All other arches build fine.
See the details here:
https://buildd.debian.org/status/package.php?p=ruby-oj&suite=sid
Let me know how I can help.

1: hurd has an additional "JSON is too deeply nested" problem

**Comment by ohler55** [comment]
It looks like the Oj test pass but then there is an 'ERROR: Test "ruby2.3" failed. Exiting.' after that. What is run by the script after the Oj tests?

**Comment by boutil** [comment]
I should have explained that. The tests are run in isolation, with the following script:
```ENV['TZ']="Europe/Paris"
SKIPPED_TESTS = [
  './test/./test_serializer.rb',
  './test/isolated/test_mimic_rails_before.rb',
  './test/isolated/test_mimic_rails_after.rb',
  './test/./test_bigd.rb',
]

success=true
Dir.glob("./test/{isolated,.}/test*.rb").each do |f|
  # we'd like to not have rails in Build-Depends, but this means we can't test the rails integration.
  next if SKIPPED_TESTS.include?(f)
  puts "-------- running #{f} test ------- "
  #system("TZ='Europe/Paris' #{ENV['RUBY_TEST_BIN']} -I#{ENV['RUBYLIB']} #{f}") or success=false
  system("#{ENV['RUBY_TEST_BIN']} -I#{ENV['RUBYLIB']} #{f}") or begin
    puts "E: Test #{f} has failed."
    success=false
  end
end

exit(1) unless(success)
```
The scripts ends with an non zero error code if one of the tests fail, but in any case, all the tests are run.

In the case, we are interested in, close to the end we find (by looking for the keyword "failed")
```
-------- running ./test/./test_various.rb test ------- 
Run options: --seed 41393

# Running:

......................................................................................F........................................

Finished in 0.019986s, 6354.3794 runs/s, 11107.6554 assertions/s.

  1) Failure:
Juice#test_float_parse [./test/./test_various.rb:185]:
Expected: BigDecimal
  Actual: Float

127 runs, 222 assertions, 1 failures, 0 errors, 0 skips
E: Test ./test/./test_various.rb has failed.
```
which is the same error as in my first message.

**Comment by ohler55** [comment]
Thanks. Let me try the easy changes first. Making sure the test i using bigdecimal as auto. I checked in a version. In the mean time I will look at how a 32 bit system might cause the problem identified.

**Comment by ohler55** [comment]
Did the change in the test make any difference?

**Comment by boutil** [comment]
No, it didn't make any difference. I should say that above, I said it was the same error as in my first message. Actually, the failure is in the same test block, but not on the same line...
With the test modification, I can still see a failure at line 185 for test_various.rb.

**Comment by ohler55** [comment]
Thank you. I'll have to add some instrumentation.

**Comment by ohler55** [comment]
I think I found the BigDecimal/Float issue. I created a branch named "floats". If you have the time please give it a try. If that fails I will add instrumentation.

**Comment by boutil** [comment]
It tried to build the floats branch. It builds and all tests are now passing on i386, am64, and arm.

**Comment by ohler55** [comment]
released fixes

**Comment by boutil** [comment]
I noticed you haven't removed the comment blocks from the problematic test in test_various.rb. Is it intentional?

**Comment by ohler55** [comment]
No, it is not. Fixed now.
