### ISSUE TITLE
OJ 3.10.7 breaks existing float parsing in JSON.parse compared to 3.10.6

### ISSUE THREAD

**Issue by kitsunde** [ohler55/oj#610]
I'm assuming it's actually a bug to change the parsing behaviour in a patch release like this. I'm loading OJ just by doing `Oj.optimize_rails()`

In 3.10.6

```ruby
JSON.parse('{"id": 20.0000000000000000000000}')
=> {"id"=>20.0}
```

In 3.10.7

```ruby
JSON.parse('{"id": 20.0000000000000000000000}')
=> {"id"=>0.0037294240988460484}
```

In both cases, it's a `Float`. It's not clear to me how to revert to the previous behaviour if at all possible, so we've pinned it to 3.10.6 now.

**Comment by ohler55** [comment]
Clearly a bug. I'll look at it tonight. If you can try the develop branch, that is a candidate for release. It makes changes to float parsing again.

It is also a patch release trying to fix the parsing deviations. Apparently 3.10.7 was a step backwards though.

**Comment by ohler55** [comment]
Released 3.10.8 which fixes this issue.

**Comment by pravi** [comment]
3.10.7 tests failed on i386, full log https://buildd.debian.org/status/fetch.php?pkg=ruby-oj&arch=i386&ver=3.10.7-1&stamp=1595531289&raw=0

and 3.10.8 tests failed on armel and armhf, full log https://buildd.debian.org/status/fetch.php?pkg=ruby-oj&arch=armel&ver=3.10.8-1&stamp=1595772207&raw=0

**Comment by ohler55** [comment]
I can see 3.10.8 has fixed all the 3.10.7 failures except for the now you listed which is due to precision on the 17th digit. I believe the fix for that is to change the test. Would you agree?

**Comment by pravi** [comment]
It looks like it, but I will be able to confirm this only after build for i386 is completed. You can see the status here https://buildd.debian.org/status/package.php?p=ruby-oj Once status of the i386 row in that table changes to green, we can be sure.

**Comment by ohler55** [comment]
Is there anyway to pre-check before I do a release?

**Comment by pravi** [comment]
Its position in the build queue is 9 now, https://buildd.debian.org/status/architecture.php?a=i386&suite=sid it will be tried when next server for i386 is available.

I have access to machines on these architectures. I can test it if you provide me a patch.

**Comment by ohler55** [comment]
Cool, will wait to see what other errors there are. Are you able run a specific branch or do you need a certain formatted patch file to run?

**Comment by pravi** [comment]
I can create required patch from branch/commits. 

I can see the original failure in i386 is not fixed yet https://buildd.debian.org/status/fetch.php?pkg=ruby-oj&arch=i386&ver=3.10.8-1&stamp=1595782281&raw=0

**Comment by pravi** [comment]
Though previously it was 8+1 failures. Now only 1 failure. So it is better than before.

**Comment by ohler55** [comment]
I pushed a `float-testing` branch. Gave up on trying to generate what the JSON gem does and just call the Ruby converter. If someone wants fast over the "exactly like the JSON gem" they can use the fast option.

**Comment by pravi** [comment]
I picked this commit https://github.com/ohler55/oj/commit/3c1c8964341c805977dbe6cbeb573d48489c726d.patch from `float-tests` branch, but it still failed on i386.

```
-------- running test/tests_mimic.rb test -------
Loaded suite test/tests_mimic
Started
F
=======================================================================================================================
     142:   end
     143:
     144:   def test_JSON
  => 145:     assert_equal @json, JSON(@hash)
     146:     assert_equal @hash, JSON(@json)
     147:   end
     148: end
/home/praveen/ruby-oj-3.10.8/test/json_gem/json_common_interface_test.rb:145:in `test_JSON'
<"{\"a\":2,\"b\":5.23683071,\"c\":\"c\",\"d\":[1,\"b\",3.14],\"e\":{\"foo\":\"bar\"},\"g\":\"\\\"\\u0000\\u001f\",\"h\"
:1000.0,\"i\":0.001}"> expected but was                                                                                
<"{\"a\":2,\"b\":5.2368307099999996,\"c\":\"c\",\"d\":[1,\"b\",3.14],\"e\":{\"foo\":\"bar\"},\"g\":\"\\\"\\u0000\\u001f\",\"h\":1000.0,\"i\":0.001}">                                                                                         

diff:
? {"a":2,"b":5.23683071        ,"c":"c","d":[1,"b",3.14],"e":{"foo":"bar"},"g":"\"\u0000\u001f","h":1000.0,"i":0.001}
?                     099999996
Failure: test_JSON(JSONCommonInterfaceTest)
```

**Comment by ohler55** [comment]
Thats disturbing. Ruby code generated that output. Okay, back to the drawing board.

**Comment by ohler55** [comment]
Maybe this version will work. I changed the output to use the Ruby float writer when in compat mode. Same branch.

**Comment by pravi** [comment]
My previous test was only with i386 which was passing, though tests are still failing on armel, armhf and mpisel. 

Logs https://buildd.debian.org/status/fetch.php?pkg=ruby-oj&arch=armel&ver=3.10.13-1&stamp=1598615020&raw=0
https://buildd.debian.org/status/fetch.php?pkg=ruby-oj&arch=armhf&ver=3.10.13-1&stamp=1598615188&raw=0
https://buildd.debian.org/status/fetch.php?pkg=ruby-oj&arch=mipsel&ver=3.10.13-1&stamp=1598615251&raw=0

```
 1) Failure:
CustomJuice#test_float_parse_fast [/<<PKGBUILDDIR>>/test/test_custom.rb:129]:
Expected: "12.12345678901235"
  Actual: "12.12345678901234"

482 runs, 8980 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by ohler55** [comment]
I think you might not be using the current develop branch. This is the current line in the file https://github.com/ohler55/oj/blob/develop/test/test_custom.rb#L129. Note there is a comparison to a range and not a specific value unlike the older versions of the file.

**Comment by pravi** [comment]
Thanks, it is working on armel now. I will upload it and verify it builds on all architectures now.

**Comment by pravi** [comment]
Its all clear now, thanks for your help. Build succeeded in all supported architectures.

**Comment by ohler55** [comment]
Great, I'll make a release with the updated test.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by pravi** [comment]
Yes, we can close this. Thanks for your help.
