### ISSUE TITLE
Oj v3.13 seems to be freezing empty string values

### ISSUE THREAD

**Issue by louim** [ohler55/oj#691]
Hey! We recently updated Oj from version 3.12.3 to v3.13.1, and something changed (I guess in Oj.load?) and it is causing errors in our rails app.

Here is a reproducible test case:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", "~> 6.1.0"
  gem "sqlite3"
  gem "oj"
end

require "active_record"
require "minitest/autorun"
require "logger"
require "oj"

Oj.optimize_rails

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.json :profile
  end
end

class User < ActiveRecord::Base
  before_validation :strip_profile_fields

  def strip_profile_fields
    profile.each_value { |v| v.strip! if v.respond_to?(:strip!) }
  end
end

class BugTest < Minitest::Test
  def test_saving_with_empty_string
    User.create!(profile: { special_property: "", working_property: "hello  " })

    assert_equal 1, User.count
  end
end
```

Commenting `Oj.optimize_rails`  will make the test pass. I lacks the Oj internal knowledge to know what could have changed.

**Comment by ohler55** [comment]
Are you using Ruby 3.0.2?

**Comment by louim** [comment]
Sorry, I forgot to mention the ruby version. We’re running 2.6.8 at the moment.

**Comment by ohler55** [comment]
Ok, will try it out tonight. Not sure what changed there other than some dump optimizations.

**Comment by louim** [comment]
This is the error we're seeing when running this test case:
```
Finished in 0.003121s, 320.4101 runs/s, 0.0000 assertions/s.

  1) Error:
BugTest#test_saving_with_empty_string:
FrozenError: can't modify frozen String
    /Users/louim/Desktop/oj.rb:36:in `strip!'
    /Users/louim/Desktop/oj.rb:36:in `block in strip_profile_fields'
    /Users/louim/Desktop/oj.rb:36:in `each_value'
    /Users/louim/Desktop/oj.rb:36:in `strip_profile_fields'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:427:in `block in make_lambda'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:603:in `catch'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:603:in `block in default_terminator'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:199:in `block in halting'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:512:in `block in invoke_before'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:512:in `each'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:512:in `invoke_before'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:105:in `run_callbacks'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:824:in `_run_validation_callbacks'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activemodel-6.1.4/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activemodel-6.1.4/lib/active_model/validations.rb:337:in `valid?'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4/lib/active_record/validations.rb:68:in `valid?'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4/lib/active_record/validations.rb:84:in `perform_validations'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4/lib/active_record/validations.rb:53:in `save!'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4/lib/active_record/transactions.rb:302:in `block in save!'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4/lib/active_record/transactions.rb:302:in `save!'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4/lib/active_record/suppressor.rb:48:in `save!'
    /Users/louim/.asdf/installs/ruby/2.6.8/lib/ruby/gems/2.6.0/gems/activerecord-6.1.4/lib/active_record/persistence.rb:55:in `create!'
    /Users/louim/Desktop/oj.rb:42:in `test_saving_with_empty_string'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

It seems like empty strings are now frozen.

**Comment by ohler55** [comment]
If that is the normal use case for rails, to modified strings I can make the default for rails not to cache strings. There are two options for caching. If caching is turned off does the error still occur?

**Comment by louim** [comment]
I'm not 100% sure how to change the cache setting. Where can I find those options?

**Comment by ohler55** [comment]
Oh, sorry, `Oj.default_options = {cache_keys: false, cache_str: -1}`

**Comment by ohler55** [comment]
Is string modification something that is done in rails or is that in your code? If your code then the fix that might be better would be to use `#strip` instead of `#strip!`. The caching does give a performance improvement.

**Comment by louim** [comment]
Modification is done in the app code, but I think most people will expect json values from rails to be mutable. I agree in this specific case using `strip` would be better, but I think there is merit to having `cache_str` disabled as the default when using `Oj.optimize_rails`. I think key caching is fine.

**Comment by ohler55** [comment]
Standby for a fix soon. I reworked the caching a bit. You can also turn off caching with `:cache_keys => false` and `:cache_strings => 0` although there is a bug that still caches the zero length string which is also fixed in the upcoming release.

**Comment by ohler55** [comment]
Released v3.13.3 that should take case of this.

**Comment by toncid** [comment]
Hello @ohler55,

Thank you, but the issue still seems to persist with v3.13.4. Empty strings are frozen by default, whereas the controller code expects them not to be.

We have Oj included like this:

```ruby
Oj.optimize_rails
Oj.default_options = {mode: :rails, use_raw_json: true}
```

It is not clear what needs to be done to avoid this, but it seems that string caching (at least in the frozen form) is not optimized for Rails.

Anyway, some upgrade instructions would be preferred to know how to deal with this issue moving forward.

**Comment by ohler55** [comment]
I'll take another look. Just to make sure, are the empty strings JSON values or Object keys?

**Comment by toncid** [comment]
Values are frozen. I can definitely work around this. It seems that it is not specified whether Rails returns frozen or unfrozen strings via controller's `params` method.

As for the repro case, just a simple controller test sending blank string is sufficient:

```ruby
test 'should create object' do
  post :create, params: {
       object_id: 12345,
       transaction: {frozen_param: '', unfrozen_param: 'a'}
  }, as: :json
  ...
end

```

**Comment by ohler55** [comment]
With the default setting I see and empty string value is not frozen. If cache_keys is on then an empty string as an object key will be frozen and cache_keys is on by default. Is it just empty string keys that rails expects to not be frozen or any object key? 

Your suggestion of a notes is a good idea. Not sure where it belongs though. Maybe in the discussion tab on this repo. It seems like too much for the change log especially as I would expect additions over time.

**Comment by toncid** [comment]
> With the default setting I see and empty string value is not frozen. If cache_keys is on then an empty string as an object key will be frozen and cache_keys is on by default. Is it just empty string keys that rails expects to not be frozen or any object key?

I have no explanation what is happening then, because the unit test passes with v3.12.3 and fails with v3.13.4.

> Your suggestion of a notes is a good idea. Not sure where it belongs though. Maybe in the discussion tab on this repo. It seems like too much for the change log especially as I would expect additions over time.

Maybe into the UPGRADING.md file and just refer to it from the changelog?

**Comment by ohler55** [comment]
Here is what I ran. Are you able to put together something simple like that?

```
irb(main):001:0> x = Oj.load('{"":""}')
=> {""=>""}
irb(main):002:0> x.each_pair { |k,v| puts "k frozen?: #{k.frozen?} v frozen?: #{v.frozen?}" }
k frozen?: true v frozen?: false
=> {""=>""}
```

**Comment by toncid** [comment]
It gives a different output on my machine (macOS):

```
2.6.7 :001 > Oj::VERSION
 => "3.13.4" 
2.6.7 :002 > Oj.default_options
 => 
{:indent=>0,
 :second_precision=>3,
 :circular=>false,
 :class_cache=>true,
 :auto_define=>false,
 :symbol_keys=>false,
 :bigdecimal_as_decimal=>nil,
 :create_additions=>false,
 :use_to_json=>false,
 :use_to_hash=>false,
 :use_as_json=>false,
 :use_raw_json=>true,
 :nilnil=>false,
 :empty_string=>true,
 :allow_gc=>true,
 :quirks_mode=>true,
 :allow_invalid_unicode=>false,
 :allow_nan=>true,
 :trace=>false,
 :safe=>false,
 :float_precision=>16,
 :cache_str=>0,
 :ignore_under=>false,
 :cache_keys=>true,
 :mode=>:rails,
 :integer_range=>nil,
 :escape_mode=>:json,
 :time_format=>:unix,
 :bigdecimal_load=>:auto,
 :compat_bigdecimal=>false,
 :create_id=>"json_class",
 :space=>nil,
 :space_before=>nil,
 :object_nl=>nil,
 :array_nl=>nil,
 :nan=>:auto,
 :omit_nil=>false,
 :hash_class=>nil,
 :array_class=>nil,
 :ignore=>nil} 
2.6.7 :003 > x = Oj.load('{"":""}')
 => {""=>""} 
2.6.7 :004 > x.each_pair { |k,v| puts "k frozen?: #{k.frozen?} v frozen?: #{v.frozen?}" }
k frozen?: true v frozen?: true
 => {""=>""} 
```

**Comment by ohler55** [comment]
That's interesting. I wa using Ruby 3.0.2. I'll try 2.6.7 and figure out why they would be different. Thanks for the example. Will look into it tonight.

**Comment by toncid** [comment]
I have tried on Ruby v2.6.8 on Linux and it behaves the same. I also don't see why Ruby version would affect this behavior.

**Comment by ohler55** [comment]
I'll try some variations tonight. There must be something different in our environments. Not sure what yet though.

**Comment by ohler55** [comment]
I think we were using different modes. Anyway I think I found the issue and fixed it in the 'just-less' branch. If it works for you I'll create a release.

**Comment by toncid** [comment]
Thanks. It seems to be working fine now:

```
2.6.7 :001 > Oj::VERSION
 => "3.13.5" 
2.6.7 :002 > x = Oj.load('{"":""}')
 => {""=>""} 
2.6.7 :003 > x.each_pair { |k,v| puts "k frozen?: #{k.frozen?} v frozen?: #{v.frozen?}" }
k frozen?: true v frozen?: false
 => {""=>""} 
```

I am curious, what kind of optimization does value caching bring? In other words, maybe do a write up of how it is intended to be used (depending on the Oj mode)?

**Comment by toncid** [comment]
Also noticed that [the Oj option](https://github.com/ohler55/oj/search?q=cache_str) is named `cache_str`, whereas [the documentation](https://github.com/ohler55/oj/blob/develop/pages/Options.md#cache_strings-int) mentions `cache_strings`. 

It is probably good to have these two places aligned.

**Comment by ohler55** [comment]
I did update the docs so either will work. Maybe better to just remove one of them though.

Value cache, like key caching reduces the number of Ruby objects created if the values are expected to occur more than once. Take for example status field what has 3 different values or a log entry where the log level has discrete values. Reducing the Ruby object creation reduces memory use as well as time.

**Comment by toncid** [comment]
Thanks!

**Comment by ohler55** [comment]
Released.

**Comment by ohler55** [comment]
Ok to close?

**Comment by toncid** [comment]
Yup, looks good. Thanks!
